blog/urls.py
from django.urls import path, include
from blog import views
from blog.models import Article

# ブログ配下のURL一覧 (blog/**)
urlpatterns = [
    #path('test', views.test)
    path('', views.index),
    path('tags/<slug:slug>/', views.tags),  #blog/<<引数slug>>のURLで取得 view.py内のtagで与えられるので使用する
    path('<slug:pk>/', views.article),  #blog/<<引数pk>>のURLで取得 viewで使用する
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.views.decorators.cache import cache_page


# URL一覧
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index), #path('URL',viewsの表示メソッド)
    path('blog/',include('blog.urls')),
    path('login/',views.Login.as_view()),
    path('logout/',LogoutView.as_view()),
    path('signup/',views.signup),
    path('mypage/',views.MypageView.as_view()),
    path('contact/',views.ContactView.as_view()),
    path('pay/',views.PayView.as_view()),
    #path('cache_test/',cache_page(30)(views.cache_test)), #ページ単位でキャッシュ 保存する秒数を指定
    path('cache_test/',views.cache_test),
]

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

#ユーザー管理用マネージャー

class UserManager(BaseUserManager):
    #一般ユーザーの作成
    def create_user(self, email, password=None):
        #メアドチェック
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    #管理者用ユーザーの作成
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

#ユーザーデータ
class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True, #重複禁止
    )

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

# --- OnetoOnefieldを同時作成、Userモデル作成時にProfileを作成・紐づけ ---
from django.db.models.signals import post_save
from django.dispatch import receiver

#@receiverデコレータでハンドラ呼び出し。post_saveでsenderで与えられたモデルが保存(作成)された後に直後にある関数を呼び出し
@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    #receiverに渡された引数含む複数の引数をkwagsで取得。辞書として登録されるので、その中の「created」引数を確認
    if kwargs['created']: # post_save内にあるcreated引数を確認。レコードが新規作成分ならTrueとなる。
        from mysite.models.profile_models import Profile

        Profile.objects.create(user=kwargs['instance'])

mysite/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model
import os

def upload_image_to(instance, filename):
  user_id = str(instance.user.id)

  return os.path.join('image',user_id,filename)

class Profile(models.Model):
  # OneToOne使用  ユーザーモデルに紐づける + primary_key = Trueで主キーとする
  user = models.OneToOneField(get_user_model(),unique=True,on_delete=models.CASCADE,primary_key=True)

  username = models.CharField(default="John Doe",max_length=30)

  zipcode = models.CharField(default="",max_length=8) #郵便番号

  prefecture = models.CharField(default="",max_length=6) #都道府県

  city = models.CharField(default="",max_length=100) #都市

  address = models.CharField(default="",max_length=200) #地区番

  image = models.ImageField(default="", blank=True , upload_to=upload_image_to) #画像 URLパスが保存される

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import fields
from mysite.models.profile_models import Profile

# 認証用のフォームモデル
class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

# プロフィールのフォームモデル
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = {
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
            'image'
        }

mysite/views.py
from django import forms
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from django.contrib import messages
from mysite.forms import UserCreationForm , ProfileForm
from blog.models import Article
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.core.mail import send_mail
from django.views import View
import os

# Create your views here.

def index(request):
    # 人気順でソート
    ranks = Article.objects.order_by('-count')[:2] #降順
    objs = Article.objects.all()[:3]
    context = {
        'title' : 'Really Site',
        'articles' : objs,
        'ranks' : ranks,
    }
    return render(request, 'mysite/index.html', context)

class Login(LoginView):
    # ログイン/サインアップ用のサイトへ渡す
    template_name = 'mysite/auth.html'

    def form_valid(self,form):
        messages.success(self.request, 'ログイン完了！')
        # 親クラス(Loginview)のform_validを呼び出し。LoginViewで取得されたformが問題なければリダイレクトする オーバーライド
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request, 'ログイン失敗！')
        return super().form_invalid(form)

def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # POSTで送られたユーザー情報をチェック、保存
        if form.is_valid():
            user = form.save(commit=False)
            #user.is_active = False
            user.save()
            # ログイン
            login(request, user)
            messages.success(request, '登録完了！')
            return redirect('/')
    # ログイン/サインアップ用のサイトへ渡す
    return render(request, 'mysite/auth.html', context)

# ログイン認証状態のみアクセス可能を指定
from django.contrib.auth.mixins import LoginRequiredMixin

class MypageView(LoginRequiredMixin,View):
    context = {}
    # クラスビューを使用。各メソッドでCRUDに対する処理を記載できる
    def get(self, request):
        return render(request, 'mysite/mypage.html', self.context)

    def post(self, request):
        #POSTリクエストでhtml側のフォームから送られたデータをdjangoのフォームモデルへ入れ込む nameで各fieldの値を指定
        form = ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '送信完了')
        else:
            messages.error(request, '更新失敗')
        return render(request, 'mysite/mypage.html',self.context)

class ContactView(View):
    context = {}
    def get(self, request):
        return render(request, 'mysite/contact.html', self.context)

    def post(self, request):
        # メール設定部分
        subject = "djangoテスト用問い合わせ"
        message = "お問い合わせ内容\n 名前: {} \n メールアドレス:{} \n 内容: {}".format(
            request.POST.get('name'),
            request.POST.get('email'),
            request.POST.get('content'))
        email_from = os.environ['DEFAULT_EMAIL_FROM']
        email_to = [
            os.environ['DEFAULT_EMAIL_FROM'],
        ]

        send_mail( subject, message, email_from, email_to, fail_silently=False,)
        messages.success(request,'お問い合わせ完了しました')

        return render(request, 'mysite/contact.html', self.context)

import payjp

class PayView(View):
    payjp.api_key = os.environ['PAYJP_SECRET_KEY']
    public_key = os.environ['PAYJP_PUBLIC_KEY']
    amount = 1000

    def get(self, request, *args, **kwargs):
        context = {
            'amount': self.amount,
            'public_key': self.public_key,
        }
        return render(request, 'mysite/pay.html', context=context)
    def post(self, request, *args, **kwargs):
        # テスト用の決済アカウントを使用
        customer = payjp.Customer.create(
            email = 'example@pay.jp',
            card = request.POST.get('payjp-token')
        )
        charge = payjp.Charge.create(
            amount = self.amount,
            currency = 'jpy',
            customer = customer.id,
            description ='支払いテスト')

        context = {
            'amount': self.amount,
            'public_key': self.public_key,
            'charge':charge
        }
        return render(request, 'mysite/pay.html', context=context)

def cache_test(request):
    import datetime
    context = {
        'time': datetime.datetime.now().isoformat(),
    }
    return render(request, 'mysite/cache_test.html', context)

templates/mysite/auth.html
{% extends 'mysite/base_auth.html' %}

{% block content %}


<div class="sidenav">
     <div class="login-main-text">
               <h1 class="display-4 font-italic"><a href="/" class="text-decoration-none">ReallySite</h1></a>
         </div>
      </div>

      <div class="main">
         <div class="col-md-12 col-sm-24">
            <div class="login-form">
               <form method="POST">
               {% csrf_token %}
                  <div class="form-group">
                     <label>Email</label>
                     <input type="text" class="form-control" placeholder="email" name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}"> </div>
                  <div class="form-group">
                     <label>Password</label>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  <button type="submit" class="btn btn-black">
                     {% if 'login' in request.path %}
                        Login
                     {% elif 'signup' in request.path %}
                        Signup
                     {% endif %}
                  </button>
               </form>
                     {% if 'login' in request.path %}
                        <a class="p-2 text-center link-secondary" href="/signup/">登録はこちら</a>
                     {% elif 'signup' in request.path %}
                        <a class="p-2 text-center link-secondary" href="/login/">ログインはこちら</a>
                     {% endif %}
            </div>
         </div>
      </div>
</div>
{% endblock %}

templates/mysite/base.html
<!doctype html>
<html lang="ja">

<head>
    {% include 'mysite/snippets/head.html' %}
</head>

<body>

    {# ヘッダー部 #}
    {% include 'mysite/snippets/header.html' %}
    {# メッセージ(ログイン成功時etc)#}
    {% include 'mysite/snippets/messages.html' %}
    {# ボディ部 #}
    {% block content %}
    <h1>Base.htmlです</h1>
    {% endblock %}
    {# フッター部 #}
    {% include 'mysite/snippets/footer.html' %}

</body>

</html>

templates/mysite/base_auth.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!doctype html>
<html lang="ja">

{% load static %}
<head>
    {% include 'mysite/snippets/head.html' %}
    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href={% static 'css/login.css' %}>

</head>

<body class="vh-100 d-flex align-items-center justify-content-center bg-light">

    <!--ボディ部-->
    {% block content %}
    {% endblock %}
    <!--フッター部-->

</body>

</html>

templates/mysite/cache_test.html
キャッシュ確認用<br>
<br>
{% load cache %}

現在時刻 : {{time}}
<br>
{# cacheで囲んだ特定部分をキャッシュ化 秒数/キャッシュ名/分岐で指定#}
{% cache 30 first_cache %}
キャッシュ時刻 : {{time}}
{% endcache %}

templates/mysite/contact.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            問い合わせページ
        </h3>

        <form class="row g-3" method="POST">
            {% csrf_token %}
            <div class="col-12">
                <label class="form-label">名前</label>
                <input type="text" class="form-control" id="id_username" name="name" placeholder="name" >
            </div>
            <div class="col-12">
                <label class="form-label">メールアドレス</label>
                <input type="email" class="form-control" id="id_email" name="email" placeholder="メールアドレス" >
            </div>

            <div class="col-12">
                <label class="form-label">問い合わせ内容</label>
                <textarea name="content" class="form-control" rows="4"> </textarea>
            </div>


            <div class="col-12">
              <button type="submit" class="btn btn-primary">送信</button>
            </div>
          </form>

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>
</main>


{% endblock %}

templates/mysite/index.html

{% extends 'mysite/base.html' %}

{% block content %}
<div class="container">
   <div class="p-4 p-md-5 mb-4 rounded bg-warning">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Udemy Django講座</h1>
            <p class="lead mb-0">
                <a href="#" class="font-weight-bold">ゆっくりしていってね</a>
            </p>
        </div>
    </div>
    <div class="row mb-2">
        {% for obj in ranks %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row
            mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">
                        {% for tag in obj.tags.all %}
                            {{tag.name}}
                        {% endfor %}
                    </strong>
                    <h3 class="mb-0">{{obj.title}}</h3>
                    <div class="mb-1 text-muted">{{obj.created_at}}</div>
                    <div class="d-inline text-warning">{{obj.created_at}}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                        </svg>
                        {{ obj.count }} good
                    </div>
                    <p class="card-text mb-auto">{{obj.text | slice:":60"}}...</p>
                    <a href="/blog/{{obj.id}}" class="stretched-link"></a>
                </div>
            </div>
        </div>
        {% endfor%}

    </div>
</div>


<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                Django Lesson
            </h3>

            {% for obj in articles %}
            <div class="blog-post position-relative">
                <h2 class="blog-post-title">{{obj.title}}</h2>
                <p class="blog-post-meta">{{obj.created_at}} by
                    <a href="#">{{obj.author}}</a>
                </p>
                <p>{{obj.text | slice:":120"}}...</p>
                <a href = "/blog/{{obj.id}}" class="stretched-link">
                続きはこちら
                </a>
            </div>
            <hr>
            {% endfor%}
            <nav class="blog-pagination">
                <a class="btn btn-outline-primary" href="/blog">ブログ一覧はこちら</a>
            </nav>
        </div>
        {% include 'mysite/snippets/sidebar.html' %}
    </div>
</main>
{% endblock %}

templates/mysite/mypage.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            マイページ
        </h3>

        <form class="row g-3" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'mysite/snippets/profile_image.html' %}

            <div class="col-12">
                <label class="form-label">ユーザー名（公開されます）</label>
                {#userでデータモデルUser取得。OnetoOneで繋いでるprofileをメソッドチェーン的な用法で取ってくる #}
                <input type="text" class="form-control" id="id_username" name="username" placeholder="煉獄 杏寿郎" value ="{{user.profile.username}}">
              </div>

              <div class="col-md-2">
                <label class="form-label">郵便番号</label>
                <input type="text" class="form-control" id="id_zipcode" name="zipcode" value ="{{user.profile.zipcode}}">
              </div>
              <div class="col-md-4">
                <label class="form-label">都道府県</label>
                <select id="id_prefecture" name="prefecture" class="form-select">
                  <option selected>選択...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="col-md-6">
                <label class="form-label">市区</label>
                <input type="text" class="form-control" id="id_city" name="city" value ="{{user.profile.city}}">
              </div>

            <div class="col-12">
              <label class="form-label">住所</label>
              <input type="text" class="form-control" id="id_address" name="address" placeholder=""  value ="{{user.profile.address}}">
            </div>

            <div class="col-12">
              <button type="submit" class="btn btn-success">保存</button>
            </div>
          </form>

        </div>

        {% include 'mysite/snippets/sidebar.html' %}

    </div>
</main>


{% endblock %}

templates/mysite/pay.html
{% extends 'mysite/base.html' %}

{% block content %}
<main class="container">
   <div class="row">
        <div class="col-md-8 mb-4">
        <h3 class="pb-4 mb-4 font-italic border-bottom display-5">
          Pay demo
        </h3>

        <form method="POST">
          {% csrf_token %}

          {% if charge %}
          <p>ブランド : {{ charge.card.brand }}</p>
          <p>****-****-****-{{ charge.card.last4 }}</p>
          {% endif %}

          <script type="text/javascript"
          src="https://checkout.pay.jp"
          class="payjp-button"
          data-key="{{ public_key }}">
          </script>



        </form>

        {% include 'mysite/snippets/sidebar.html' %}
    </div>

</main>

{% endblock %}