blog/urls.py
from django.urls import path, include
from blog import views
from blog.models import Article

# ブログ配下のURL一覧 (blog/**)
urlpatterns = [
    #path('test', views.test)
    path('', views.index),
    path('tags/<slug:slug>/', views.tags),  #blog/<<引数slug>>のURLで取得 view.py内のtagで与えられるので使用する
    path('<slug:pk>/', views.article),  #blog/<<引数pk>>のURLで取得 viewで使用する
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.views.decorators.cache import cache_page


# URL一覧
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index), #path('URL',viewsの表示メソッド)
    path('blog/',include('blog.urls')),
    path('login/',views.Login.as_view()),
    path('logout/',LogoutView.as_view()),
    path('signup/',views.signup),
    path('mypage/',views.MypageView.as_view()),
    path('contact/',views.ContactView.as_view()),
    path('pay/',views.PayView.as_view()),
    #path('cache_test/',cache_page(30)(views.cache_test)), #ページ単位でキャッシュ 保存する秒数を指定
    path('cache_test/',views.cache_test),
]

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

#ユーザー管理用マネージャー

class UserManager(BaseUserManager):
    #一般ユーザーの作成
    def create_user(self, email, password=None):
        #メアドチェック
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    #管理者用ユーザーの作成
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

#ユーザーデータ
class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True, #重複禁止
    )

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

# --- OnetoOnefieldを同時作成、Userモデル作成時にProfileを作成・紐づけ ---
from django.db.models.signals import post_save
from django.dispatch import receiver

#@receiverデコレータでハンドラ呼び出し。post_saveでsenderで与えられたモデルが保存(作成)された後に直後にある関数を呼び出し
@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    #receiverに渡された引数含む複数の引数をkwagsで取得。辞書として登録されるので、その中の「created」引数を確認
    if kwargs['created']: # post_save内にあるcreated引数を確認。レコードが新規作成分ならTrueとなる。
        from mysite.models.profile_models import Profile

        Profile.objects.create(user=kwargs['instance'])

mysite/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model
import os

def upload_image_to(instance, filename):
  user_id = str(instance.user.id)

  return os.path.join('image',user_id,filename)

class Profile(models.Model):
  # OneToOne使用  ユーザーモデルに紐づける + primary_key = Trueで主キーとする
  user = models.OneToOneField(get_user_model(),unique=True,on_delete=models.CASCADE,primary_key=True)

  username = models.CharField(default="John Doe",max_length=30)

  zipcode = models.CharField(default="",max_length=8) #郵便番号

  prefecture = models.CharField(default="",max_length=6) #都道府県

  city = models.CharField(default="",max_length=100) #都市

  address = models.CharField(default="",max_length=200) #地区番

  image = models.ImageField(default="", blank=True , upload_to=upload_image_to) #画像 URLパスが保存される

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import fields
from mysite.models.profile_models import Profile

# 認証用のフォームモデル
class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

# プロフィールのフォームモデル
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = {
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
            'image'
        }

mysite/views.py
from django import forms
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from django.contrib import messages
from mysite.forms import UserCreationForm , ProfileForm
from blog.models import Article
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.core.mail import send_mail
from django.views import View
import os

# Create your views here.

def index(request):
    # 人気順でソート
    ranks = Article.objects.order_by('-count')[:2] #降順
    objs = Article.objects.all()[:3]
    context = {
        'title' : 'Really Site',
        'articles' : objs,
        'ranks' : ranks,
    }
    return render(request, 'mysite/index.html', context)

class Login(LoginView):
    # ログイン/サインアップ用のサイトへ渡す
    template_name = 'mysite/auth.html'

    def form_valid(self,form):
        messages.success(self.request, 'ログイン完了！')
        # 親クラス(Loginview)のform_validを呼び出し。LoginViewで取得されたformが問題なければリダイレクトする オーバーライド
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request, 'ログイン失敗！')
        return super().form_invalid(form)

def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # POSTで送られたユーザー情報をチェック、保存
        if form.is_valid():
            user = form.save(commit=False)
            #user.is_active = False
            user.save()
            # ログイン
            login(request, user)
            messages.success(request, '登録完了！')
            return redirect('/')
    # ログイン/サインアップ用のサイトへ渡す
    return render(request, 'mysite/auth.html', context)

# ログイン認証状態のみアクセス可能を指定
from django.contrib.auth.mixins import LoginRequiredMixin

class MypageView(LoginRequiredMixin,View):
    context = {}
    # クラスビューを使用。各メソッドでCRUDに対する処理を記載できる
    def get(self, request):
        return render(request, 'mysite/mypage.html', self.context)

    def post(self, request):
        #POSTリクエストでhtml側のフォームから送られたデータをdjangoのフォームモデルへ入れ込む nameで各fieldの値を指定
        form = ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '送信完了')
        else:
            messages.error(request, '更新失敗')
        return render(request, 'mysite/mypage.html',self.context)

class ContactView(View):
    context = {}
    def get(self, request):
        return render(request, 'mysite/contact.html', self.context)

    def post(self, request):
        # メール設定部分
        subject = "djangoテスト用問い合わせ"
        message = "お問い合わせ内容\n 名前: {} \n メールアドレス:{} \n 内容: {}".format(
            request.POST.get('name'),
            request.POST.get('email'),
            request.POST.get('content'))
        email_from = os.environ['DEFAULT_EMAIL_FROM']
        email_to = [
            os.environ['DEFAULT_EMAIL_FROM'],
        ]

        send_mail( subject, message, email_from, email_to, fail_silently=False,)
        messages.success(request,'お問い合わせ完了しました')

        return render(request, 'mysite/contact.html', self.context)

import payjp

class PayView(View):
    payjp.api_key = os.environ['PAYJP_SECRET_KEY']
    public_key = os.environ['PAYJP_PUBLIC_KEY']
    amount = 1000

    def get(self, request, *args, **kwargs):
        context = {
            'amount': self.amount,
            'public_key': self.public_key,
        }
        return render(request, 'mysite/pay.html', context=context)
    def post(self, request, *args, **kwargs):
        # テスト用の決済アカウントを使用
        customer = payjp.Customer.create(
            email = 'example@pay.jp',
            card = request.POST.get('payjp-token')
        )
        charge = payjp.Charge.create(
            amount = self.amount,
            currency = 'jpy',
            customer = customer.id,
            description ='支払いテスト')

        context = {
            'amount': self.amount,
            'public_key': self.public_key,
            'charge':charge
        }
        return render(request, 'mysite/pay.html', context=context)

def cache_test(request):
    import datetime
    context = {
        'time': datetime.datetime.now().isoformat(),
    }
    return render(request, 'mysite/cache_test.html', context)

templates/mysite/snippets/comment.html
<div>
  <h3 class="h6">コメント</h3>
  <div class="list-group">

    {% for comment in comments %}
    <a class="list-group-item list-group-item-action p-3 rounded-0">
      <p class="m-0"><small>{{comment.comment}}</small></p>
      <p class="m-0"><small>{{comment.user.profile.username}}さん {{comment.created_at}}</small></p>
    </a>
    {% endfor %}
  </div>

  {% if user.is_authenticated %}
    <form method="POST" class="my-4">
      {% csrf_token %}
      <div class="mb-2">
        <label>コメント投稿</label>
        <textarea name="comment" class="rounded-0 bg-light form-control" rows="3"></textarea>
      </div>
      <div class="text-right">
        <button class="btn btn-sm btn-outline-success" type="submit">
          コメントする
        </button>
      </div>
    <form>
  {% else %}
    <p class="my-4">
      コメント投稿するには<a href="/login">ログイン</a>
    </p>
  {% endif %}

</div>

templates/mysite/snippets/footer.html
<footer class="border-top py-5 text-center bg-light mt-4">
    <p>
        <a href="/">トップに戻る</a>
    </p>
</footer>


<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
    integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
    crossorigin="anonymous"></script>

templates/mysite/snippets/head.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-EQQSYG0KV5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EQQSYG0KV5');
</script>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!--Fontawesome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<title>Really Site</title>

templates/mysite/snippets/header.html
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-center align-item-center">
            <div class="col-4 text-center">
                <h1 class="display-4 font-italic"><a href="/" class="text-decoration-none">ReallySite</h1></a>
            </div>
        </div>
    </header>
    <div class="py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 link-secondary" href="/blog/">ブログ</a>
            <a class="p-2 link-secondary" href="/contact/">お問い合わせ</a>
            {# ログイン選択部分#}
            {% if user.is_authenticated %}
            <div>
                <a class="p-2 text-center link-secondary" href="/logout/">ログアウト</a>
                <a class="p-2 text-center link-secondary" href="/mypage/">マイページ</a>
            </div>
            {% else %}
            <div>
                <a class="p-2 text-center link-secondary" href="/login/">ログイン</a>
                <a class="btn btn-outline-info" href="/signup/">新規登録</a>
            </div>
            {% endif %}
        </nav>
    </div>
</div>


templates/mysite/snippets/like_count.html
  <form method="POST" class="d-inline">
      {% csrf_token %}
      {#like_count要のボタンを作成 value与えないと値が来てないと判断されるので注意 #}
      <input type="hidden" name="like_count" value="true">
      <button type="submit" class="btn btn-sm btn-outline-warning">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
          </svg>
          {{ article.count }} good
      </button>
  </form>

templates/mysite/snippets/messages.html
{% comment %} ソースコード内でのコメント 外部から見れない形となる  {% endcomment %}
{% for msg in messages %}
<nav class="py-2 {{ msg.tags }}">
  <div class= "container">
    {{msg}}
  </div>
</nav>
{% endfor %}

templates/mysite/snippets/pagination.html
           
<nav class="blog-pagination">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            {% if page_obj.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}">next</a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</nav>

templates/mysite/snippets/pr_in_article.html
{% load static %}

{% for tag in article.tags.all %}
  {% if 'PR' in tag.name %}
  <a href="">"
    <img src="{% static 'mysite/link-img2.jpg' %}" width="75%" height=100>
  </a>
  {% endif %}
{% endfor %}

templates/mysite/snippets/profile_image.html
<label>プロフィール画像</label>

<label id="id_image_label" for="id_image">
  <!-- default upload -->
  <div id="no_image" class="{% if user.profile.image != '' %}d-none{% endif %} border rounded-circle bg-light" style="width:150px; height:150px;">
    <div class="m-auto p-4">
      <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-cloud-upload" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
        <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z"/>
      </svg>
    </div>
  </div>

  {# 画像がある場合は表示 d-noneクラスを用いて画像の非表示を制御 #}
  <img id="image_preview" class="{% if user.profile.image == '' %}d-none{% endif %} border rounded-circle" style="width: 150px; height:150px; object-fit; cover;" src="https://storage.googleapis.com/really-site/{{ user.profile.image }}" >

</label>

{# 画像アップデート部 #}
<div class="d-none">
  {#画像部分が変化時、previewImage関数を実行#}
  <input type="file" accept="image/*" id="id_image" name="image" onchange="previewImage(this)">
</div>

{# 画像プレビュー #}

<script>
  function previewImage(elem){
    // HTML5で追加されたファイル入出力用の新規クラスを使用
    var fileReader = new FileReader();
    // FileReaderがtrueを返す = ファイル読み込み成功時に以下のfunctionを実行
    fileReader.onload = (function(){
      // 指定したIDタグの物に対し、d-noneクラスの消去を実行。
      document.getElementById("image_preview").classList.remove("d-none");
      document.getElementById("no_image").classList.add("d-none");
      // 中身データを取得しimage_previewタグのsrcにセット
      document.getElementById("image_preview").src = fileReader.result;
    });
    fileReader.readAsDataURL(elem.files[0]);
  }

</script>

templates/mysite/snippets/sidebar.html
{% load static %}
{% load cache %}

{% cache 86400 sidebar%}
<aside class="col-md-4">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">
            ふじサンについて
        </h4>
        <p class="mb-0">ようこそMy講座へ！</p>
    </div>

    <figure class="figure">
        <img class="figure-img img-fluid rounded"
        src = "{% static 'mysite/link-img.jpg' %}">
        <figcaption class="figure-caption text-center font-italic small">
            <span class="text-muted"> 花の画像</span>
        </figcaption>
    </figure>


    <figure class="figure">
        <img class="figure-img img-fluid rounded"
        src = "{% static 'mysite/img2.jpg' %}">
        <figcaption class="figure-caption text-center font-italic small">
            <a class="text-muted" href="https://pixabay.com/ja/users/saydung89-18713596/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5960112">Piyapong Saydaung</a>による<a class="text-muted" href="https://pixabay.com/ja/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=5960112">Pixabay</a>からの画像
        </figcaption>
    </figure>
<

    <figure class="figure">
        <img class="figure-img img-fluid rounded"
        src = "{% static 'mysite/img1.jpg' %}">
        <figcaption class="figure-caption text-center font-italic small">
            <a class="text-muted" href="https://pixabay.com/ja/users/erik_karits-15012370/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=6405362">Erik Karits</a>による<a class="text-muted" href="https://pixabay.com/ja/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=6405362">Pixabay</a>からの画像
        </figcaption>
    </figure>
</aside>

{% endcache %}

templates/mysite/snippets/tag.html
{% for tag in article.tags.all %}
<a href='/blog/tags/{{tag.slug}}/' class="btn btn-sm btn-outline-secondary">
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tag" viewBox="0 0 16 16">
  <path d="M6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-1 0a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0z"/>
  <path d="M2 1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 1 6.586V2a1 1 0 0 1 1-1zm0 5.586 7 7L13.586 9l-7-7H2v4.586z"/>
</svg>
  {{tag.name}}
</a>
{% endfor %}